Imports System
Imports Dashboard_UnderlyingDataWin.nwindDataSetTableAdapters

Namespace Dashboard_UnderlyingDataWin
	Partial Public Class SalesDashboard
		Inherits DevExpress.DashboardCommon.Dashboard

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			salesPersonTableAdapter1.Fill(nwindDataSet3.SalesPerson)
		End Sub

		Private Sub SalesDashboard_DashboardLoading(ByVal sender As Object, ByVal e As EventArgs) Handles Me.DashboardLoading
			Dim categories As New SalesPersonTableAdapter()
			categories.Fill(Me.nwindDataSet1.SalesPerson)
		End Sub
	End Class
End Namespace
